version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: dev
  assignees:
  - keindev
  labels:
  - dependencies
