pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - status-success=Travis CI - Pull Request
          - '#review-requested=0'
          - '#changes-requested-reviews-by=0'
          - '#commented-reviews-by=0'
          - base=dev
          - author=dependabot-preview[bot]
      actions:
          label:
              add: [automatic]
          merge:
              method: merge
              strict: smart
          delete_head_branch: ~
