version: 1
update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'daily'
      target_branch: 'dev'
      default_assignees:
          - keindev
      default_labels:
          - dependencies
